import Head from 'next/head'
import { fromAndTo } from './utils'
import { useEffect, useState } from 'react'

export default function Home() {
  const [gradients, setGradients] = useState('')
  
  useEffect(() => {
    setGradients(fromAndTo());
  }, []);

  return (
    <div className="w-screen">
      <Head>
        <title>Glowing Octo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/279/octopus_1f419.png" />
      </Head>

      <main className="w-screen h-screen md:p-48 sm:p-12">
        <div className="h-1/6" />
        <h1 className="text-4xl">
        🐙
        </h1>
        <div className="flex w-full flex-wrap">
          <h1 className="font-bold text-4xl font-extrabold mr-20">
            Welcome to the
            <br/>
            <span className={`text-transparent bg-clip-text bg-gradient-to-br ${gradients}`}>
            glowing-octo 
            </span>
            <br/>sentiment checker
          </h1>
            <ul className="list-none md:mx-0">
              <li>
                <code className="font-code">1. Load the Model</code>
              </li>
              <li>
                <code className="font-code">2. Give Your Input</code>
              </li>
              <li>
                <code className="font-code">3. Hit enter to see your sentiment</code>
              </li>
            </ul>
          <div className="w-full">
            <input 
              className='w-full bg-white focus:outline-none focus:ring focus:ring-gray-900 focus:border-gray-900 p-5 mt-5 rounded-sm'
              type="text" 
              placeholder="start typing an emotionally loaded sentence"
              ref={input => input && input.focus()}/>
          </div>
        </div>

      </main>
    </div>
  )
}
